import type { QuizQuestion } from '@/types/quiz'
import type { Category } from '@/utils/constants'

const shuffle = <T>(arr: T[]): T[] => [...arr].sort(() => Math.random() - 0.5)

interface WordEntry {
  english: string
  swedish: string
  emoji: string
}

const WORD_BANKS: Record<string, WordEntry[]> = {
  'Body Parts': [
    { english: 'Head', swedish: 'Huvud', emoji: '👤' },
    { english: 'Eye', swedish: 'Öga', emoji: '👁️' },
    { english: 'Nose', swedish: 'Näsa', emoji: '👃' },
    { english: 'Ear', swedish: 'Öra', emoji: '👂' },
    { english: 'Mouth', swedish: 'Mun', emoji: '👄' },
    { english: 'Hand', swedish: 'Hand', emoji: '✋' },
    { english: 'Foot', swedish: 'Fot', emoji: '🦶' },
    { english: 'Arm', swedish: 'Arm', emoji: '💪' },
    { english: 'Leg', swedish: 'Ben', emoji: '🦵' },
    { english: 'Finger', swedish: 'Finger', emoji: '☝️' },
    { english: 'Forehead', swedish: 'Panna', emoji: '🤦' },
    { english: 'Chin', swedish: 'Haka', emoji: '🤔' },
    { english: 'Cheek', swedish: 'Kind', emoji: '😊' },
    { english: 'Hair', swedish: 'Hår', emoji: '💇' },
    { english: 'Face', swedish: 'Ansikte', emoji: '😶' },
    { english: 'Throat', swedish: 'Hals', emoji: '🗣️' },
    { english: 'Neck', swedish: 'Nacke', emoji: '🧣' },
    { english: 'Shoulder', swedish: 'Axel', emoji: '🤷' },
    { english: 'Elbow', swedish: 'Armbåge', emoji: '🦾' },
    { english: 'Chest', swedish: 'Bröst', emoji: '🫁' },
    { english: 'Stomach', swedish: 'Mage', emoji: '🍽️' },
    { english: 'Back', swedish: 'Rygg', emoji: '🧘' },
    { english: 'Butt', swedish: 'Rumpa', emoji: '🍑' },
    { english: 'Hip', swedish: 'Höft', emoji: '💃' },
    { english: 'Thigh', swedish: 'Lår', emoji: '🍗' },
    { english: 'Knee', swedish: 'Knä', emoji: '🧎' },
    { english: 'Calf', swedish: 'Vad', emoji: '🏃' },
    { english: 'Toe', swedish: 'Tå', emoji: '👣' },
    { english: 'Body', swedish: 'Kropp', emoji: '🧍' },
  ],

  Fruits: [
    { english: 'Apple', swedish: 'Äpple', emoji: '🍎' },
    { english: 'Banana', swedish: 'Banan', emoji: '🍌' },
    { english: 'Orange', swedish: 'Apelsin', emoji: '🍊' },
    { english: 'Grape', swedish: 'Vindruva', emoji: '🍇' },
    { english: 'Strawberry', swedish: 'Jordgubbe', emoji: '🍓' },
    { english: 'Mango', swedish: 'Mango', emoji: '🥭' },
    { english: 'Lemon', swedish: 'Citron', emoji: '🍋' },
    { english: 'Pear', swedish: 'Päron', emoji: '🍐' },
    { english: 'Peach', swedish: 'Persika', emoji: '🍑' },
    { english: 'Cherry', swedish: 'Körsbär', emoji: '🍒' },
    { english: 'Pineapple', swedish: 'Ananas', emoji: '🍍' },
    { english: 'Apricot', swedish: 'Aprikos', emoji: '🟠' },
    { english: 'Avocado', swedish: 'Avokado', emoji: '🥑' },
    { english: 'Blackberry', swedish: 'Björnbär', emoji: '🫐' },
    { english: 'Blueberry', swedish: 'Blåbär', emoji: '🔵' },
    { english: 'Blood orange', swedish: 'Blodapelsin', emoji: '🍊' },
    { english: 'Clementine', swedish: 'Clementin', emoji: '🍊' },
    { english: 'Fig', swedish: 'Fikon', emoji: '🌰' },
    { english: 'Pomegranate', swedish: 'Granatäpple', emoji: '❤️' },
    { english: 'Grapefruit', swedish: 'Grapefrukt', emoji: '🍈' },
    { english: 'Raspberry', swedish: 'Hallon', emoji: '🍓' },
    { english: 'Kiwi', swedish: 'Kiwi', emoji: '🥝' },
    { english: 'Coconut', swedish: 'Kokosnöt', emoji: '🥥' },
    { english: 'Gooseberry', swedish: 'Krusbär', emoji: '🟢' },
    { english: 'Lime', swedish: 'Lime', emoji: '🍋' },
    { english: 'Lingonberry', swedish: 'Lingon', emoji: '🫐' },
    { english: 'Melon', swedish: 'Melon', emoji: '🍈' },
    { english: 'Nectarine', swedish: 'Nektarin', emoji: '🍑' },
    { english: 'Olive', swedish: 'Oliv', emoji: '🫒' },
    { english: 'Passion fruit', swedish: 'Passionsfrukt', emoji: '💛' },
    { english: 'Plum', swedish: 'Plommon', emoji: '🟣' },
    { english: 'Raisin', swedish: 'Russin', emoji: '🍇' },
    { english: 'Wild strawberry', swedish: 'Smultron', emoji: '🍓' },
    { english: 'Watermelon', swedish: 'Vattenmelon', emoji: '🍉' },
    { english: 'Redcurrant', swedish: 'Rött vinbär', emoji: '🔴' },
    { english: 'Blackcurrant', swedish: 'Svart vinbär', emoji: '⚫' },
  ],

  Vegetables: [
    { english: 'Carrot', swedish: 'Morot', emoji: '🥕' },
    { english: 'Potato', swedish: 'Potatis', emoji: '🥔' },
    { english: 'Onion', swedish: 'Lök', emoji: '🧅' },
    { english: 'Tomato', swedish: 'Tomat', emoji: '🍅' },
    { english: 'Cucumber', swedish: 'Gurka', emoji: '🥒' },
    { english: 'Broccoli', swedish: 'Broccoli', emoji: '🥦' },
    { english: 'Spinach', swedish: 'Spenat', emoji: '🌿' },
    { english: 'Bell pepper', swedish: 'Paprika', emoji: '🫑' },
    { english: 'Garlic', swedish: 'Vitlök', emoji: '🧄' },
    { english: 'Pea', swedish: 'Ärta', emoji: '🫛' },
    { english: 'Eggplant', swedish: 'Aubergine', emoji: '🍆' },
    { english: 'Bean', swedish: 'Böna', emoji: '🫘' },
    { english: 'Brussels sprouts', swedish: 'Brysselkål', emoji: '🥦' },
    { english: 'Chili', swedish: 'Chili', emoji: '🌶️' },
    { english: 'Kale', swedish: 'Grönkål', emoji: '🥬' },
    { english: 'Artichoke', swedish: 'Kronärtskocka', emoji: '💚' },
    { english: 'Cabbage', swedish: 'Kål', emoji: '🥬' },
    { english: 'Lentil', swedish: 'Lins', emoji: '🫘' },
    { english: 'Corn', swedish: 'Majs', emoji: '🌽' },
    { english: 'Mint', swedish: 'Mynta', emoji: '🌿' },
    { english: 'Parsley', swedish: 'Persilja', emoji: '🌿' },
    { english: 'Pumpkin', swedish: 'Pumpa', emoji: '🎃' },
    { english: 'Radish', swedish: 'Rädisa', emoji: '🔴' },
    { english: 'Beetroot', swedish: 'Rödbeta', emoji: '🟣' },
    { english: 'Lettuce', swedish: 'Sallad', emoji: '🥬' },
    { english: 'Celery', swedish: 'Selleri', emoji: '🌿' },
    { english: 'Asparagus', swedish: 'Sparris', emoji: '🌱' },
    { english: 'Mushroom', swedish: 'Svamp', emoji: '🍄' },
    { english: 'Sweet potato', swedish: 'Sötpotatis', emoji: '🍠' },
    { english: 'Horseradish', swedish: 'Pepparrot', emoji: '🌿' },
  ],

  Groceries: [
    // Dairy & staples
    { english: 'Bread', swedish: 'Bröd', emoji: '🍞' },
    { english: 'Milk', swedish: 'Mjölk', emoji: '🥛' },
    { english: 'Eggs', swedish: 'Ägg', emoji: '🥚' },
    { english: 'Butter', swedish: 'Smör', emoji: '🧈' },
    { english: 'Cheese', swedish: 'Ost', emoji: '🧀' },
    { english: 'Rice', swedish: 'Ris', emoji: '🍚' },
    { english: 'Sugar', swedish: 'Socker', emoji: '🍬' },
    { english: 'Salt', swedish: 'Salt', emoji: '🧂' },
    { english: 'Flour', swedish: 'Mjöl', emoji: '🌾' },
    { english: 'Coffee', swedish: 'Kaffe', emoji: '☕' },
    { english: 'Cream', swedish: 'Grädde', emoji: '🥛' },
    { english: 'Margarine', swedish: 'Margarin', emoji: '🧈' },
    { english: 'Baking powder', swedish: 'Bakpulver', emoji: '🥄' },
    { english: 'Oatmeal', swedish: 'Havregryn', emoji: '🥣' },
    { english: 'Oats', swedish: 'Havre', emoji: '🌾' },
    { english: 'Olive oil', swedish: 'Olivolja', emoji: '🫒' },
    { english: 'Vinegar', swedish: 'Vinäger', emoji: '🫙' },
    // Meat
    { english: 'Bacon', swedish: 'Bacon', emoji: '🥓' },
    { english: 'Fish', swedish: 'Fisk', emoji: '🐟' },
    { english: 'Pork', swedish: 'Fläsk', emoji: '🥩' },
    { english: 'Turkey', swedish: 'Kalkon', emoji: '🦃' },
    { english: 'Sausage', swedish: 'Korv', emoji: '🌭' },
    { english: 'Crab', swedish: 'Krabba', emoji: '🦀' },
    { english: 'Chicken', swedish: 'Kyckling', emoji: '🍗' },
    { english: 'Meat', swedish: 'Kött', emoji: '🥩' },
    { english: 'Ham', swedish: 'Skinka', emoji: '🍖' },
    { english: 'Steak', swedish: 'Stek', emoji: '🥩' },
    { english: 'Venison', swedish: 'Vilt', emoji: '🦌' },
    { english: 'Beef', swedish: 'Biff', emoji: '🥩' },
    // Seafood
    { english: 'Lobster', swedish: 'Hummer', emoji: '🦞' },
    { english: 'Salmon', swedish: 'Lax', emoji: '🐟' },
    { english: 'Mackerel', swedish: 'Makrill', emoji: '🐠' },
    { english: 'Clams', swedish: 'Musslor', emoji: '🦪' },
    { english: 'Oyster', swedish: 'Ostron', emoji: '🦪' },
    { english: 'Prawns', swedish: 'Räkor', emoji: '🦐' },
    { english: 'Herring', swedish: 'Sill', emoji: '🐡' },
    { english: 'Cod', swedish: 'Torsk', emoji: '🐟' },
    // Baked & prepared
    { english: 'Bun', swedish: 'Bulle', emoji: '🫓' },
    { english: 'Porridge', swedish: 'Gröt', emoji: '🍲' },
    { english: 'Cake', swedish: 'Kaka', emoji: '🎂' },
    { english: 'Biscuit', swedish: 'Kex', emoji: '🍪' },
    { english: 'Macaroni', swedish: 'Makaroner', emoji: '🍝' },
    { english: 'Pancakes', swedish: 'Pannkakor', emoji: '🥞' },
    { english: 'Pie', swedish: 'Paj', emoji: '🥧' },
    { english: 'Pasta', swedish: 'Pasta', emoji: '🍝' },
    { english: 'Pudding', swedish: 'Pudding', emoji: '🍮' },
    { english: 'Sandwich', swedish: 'Smörgås', emoji: '🥪' },
    { english: 'Soup', swedish: 'Soppa', emoji: '🍲' },
    { english: 'Stew', swedish: 'Stuvning', emoji: '🍲' },
    { english: 'Waffle', swedish: 'Våffla', emoji: '🧇' },
    { english: 'Spaghetti', swedish: 'Spaghetti', emoji: '🍝' },
    { english: 'Cereals', swedish: 'Flingor', emoji: '🥣' },
    // Condiments
    { english: 'Ketchup', swedish: 'Ketchup', emoji: '🍅' },
    { english: 'Mayonnaise', swedish: 'Majonnäs', emoji: '🫙' },
    { english: 'Marmalade', swedish: 'Marmelad', emoji: '🍊' },
    { english: 'Mustard', swedish: 'Senap', emoji: '🌭' },
    { english: 'Jam', swedish: 'Sylt', emoji: '🍓' },
    { english: 'Spices', swedish: 'Kryddor', emoji: '🫙' },
    // Spices & herbs
    { english: 'Basil', swedish: 'Basilika', emoji: '🌿' },
    { english: 'Curry', swedish: 'Curry', emoji: '🍛' },
    { english: 'Dill', swedish: 'Dill', emoji: '🌿' },
    { english: 'Cinnamon', swedish: 'Kanel', emoji: '🟤' },
    { english: 'Cardamom', swedish: 'Kardemumma', emoji: '🌿' },
    { english: 'Nutmeg', swedish: 'Muskot', emoji: '🟤' },
    { english: 'Oregano', swedish: 'Oregano', emoji: '🌿' },
    { english: 'Pepper', swedish: 'Peppar', emoji: '🌶️' },
    { english: 'Saffron', swedish: 'Saffran', emoji: '🌼' },
    { english: 'Ginger', swedish: 'Ingefära', emoji: '🟡' },
    // Sweets & desserts
    { english: 'Chocolate', swedish: 'Choklad', emoji: '🍫' },
    { english: 'Ice cream', swedish: 'Glass', emoji: '🍦' },
    { english: 'Cupcake', swedish: 'Muffins', emoji: '🧁' },
    { english: 'Candy', swedish: 'Godis', emoji: '🍬' },
    // Drinks
    { english: 'Tea', swedish: 'Te', emoji: '🍵' },
    { english: 'Fruit juice', swedish: 'Fruktjuice', emoji: '🧃' },
    { english: 'Juice', swedish: 'Juice', emoji: '🧃' },
    { english: 'Soda', swedish: 'Läsk', emoji: '🥤' },
    { english: 'Cordial', swedish: 'Saft', emoji: '🧃' },
    { english: 'Wine', swedish: 'Vin', emoji: '🍷' },
    { english: 'Beer', swedish: 'Öl', emoji: '🍺' },
  ],
}

export const generateQuestions = (category: Category, count = 10): QuizQuestion[] => {
  const bank = WORD_BANKS[category]
  const allSwedish = Object.values(WORD_BANKS)
    .flat()
    .map((w) => w.swedish)

  return shuffle(bank)
    .slice(0, count)
    .map((word, i) => {
      const distractors = shuffle(allSwedish.filter((s) => s !== word.swedish)).slice(0, 3)
      const options = shuffle([word.swedish, ...distractors])
      return {
        id: `${category}-${i}`,
        englishWord: word.english,
        swedishWord: word.swedish,
        emoji: word.emoji,
        options,
        correctIndex: options.indexOf(word.swedish),
        pointValue: 50,
      }
    })
}
